// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The Ebitengine Authors

//go:build ignore

// gen_fast_func generates zero-allocation closures for RegisterFunc's fast path.
// The output file is zz_fast_func.go.
//
// It emits:
//   - registerFastFunc: int-only closures for 0..10 args
//   - fastCall0..fastCall10: int-only syscall wrappers
//   - fastCallIF: shared int+float backend
//   - registerFastFuncFloat: dispatcher for trailing float
//   - registerFastFuncFloat32x1: N ints + 1 trailing float32, N=0..9
//   - registerFastFuncFloat64x1: N ints + 1 trailing float64, N=0..9
//   - registerFastFuncInterleavedFloat32x1: 1 float32 at any position, 2..10 total args
//   - registerFastFuncFloatN: MakeFunc fallback for multi/interleaved float
//   - forceFuncPtr: unsafe func-ptr swap
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
)

const maxIntArgs = 10

func main() {
	var buf bytes.Buffer
	buf.WriteString(`// Code generated by gen_fast_func.go; DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The Ebitengine Authors

//go:build darwin || freebsd || linux || netbsd || windows

package purego

import (
	"math"
	"reflect"
	"unsafe"
)

`)

	writeRegisterFastFunc(&buf)
	writeFastCallFunctions(&buf)
	writeFastCallIF(&buf)
	writeRegisterFastFuncFloat(&buf)
	writeRegisterFastFuncFloat32x1(&buf)
	writeRegisterFastFuncFloat64x1(&buf)
	writeRegisterFastFuncInterleavedFloat32x1(&buf)
	writeRegisterFastFuncFloatN(&buf)
	writeForceFuncPtr(&buf)

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("gofmt: %v\n%s", err, buf.String())
	}
	if err := os.WriteFile("zz_fast_func.go", src, 0644); err != nil {
		log.Fatal(err)
	}
}

// argList returns "a1, a2, ..., aN" for n args.
func argList(n int) string {
	if n == 0 {
		return ""
	}
	parts := make([]string, n)
	for i := range n {
		parts[i] = fmt.Sprintf("a%d", i+1)
	}
	return strings.Join(parts, ", ")
}

// paramList returns "a1, a2, ..., aN uintptr" for n args.
func paramList(n int) string {
	if n == 0 {
		return ""
	}
	return argList(n) + " uintptr"
}

// writeRegisterFastFunc emits the int-only dispatcher: 0..maxIntArgs.
func writeRegisterFastFunc(buf *bytes.Buffer) {
	buf.WriteString(`// registerFastFunc sets fn to a zero-allocation closure that calls cfn
// without using reflect.MakeFunc.
func registerFastFunc(fn reflect.Value, cfn uintptr, numArgs int, hasReturn bool) {
	switch numArgs {
`)
	for n := 0; n <= maxIntArgs; n++ {
		params := paramList(n)
		args := argList(n)
		callArgs := "cfn"
		if args != "" {
			callArgs += ", " + args
		}
		fmt.Fprintf(buf, "\tcase %d:\n", n)
		fmt.Fprintf(buf, "\t\tif hasReturn {\n")
		fmt.Fprintf(buf, "\t\t\timpl := func(%s) uintptr { return fastCall%d(%s) }\n", params, n, callArgs)
		fmt.Fprintf(buf, "\t\t\tforceFuncPtr(fn, &impl)\n")
		fmt.Fprintf(buf, "\t\t} else {\n")
		fmt.Fprintf(buf, "\t\t\timpl := func(%s) { fastCall%d(%s) }\n", params, n, callArgs)
		fmt.Fprintf(buf, "\t\t\tforceFuncPtr(fn, &impl)\n")
		fmt.Fprintf(buf, "\t\t}\n")
	}
	buf.WriteString("\t}\n}\n\n")
}

// writeFastCallFunctions emits fastCall0..fastCall{maxIntArgs}.
func writeFastCallFunctions(buf *bytes.Buffer) {
	for n := 0; n <= maxIntArgs; n++ {
		params := "cfn"
		if n > 0 {
			params += ", " + argList(n)
		}

		fmt.Fprintf(buf, "func fastCall%d(%s uintptr) uintptr {\n", n, params)
		buf.WriteString("\ts := thePool.Get().(*syscall15Args)\n")
		buf.WriteString("\ts.fn = cfn\n")

		// Set a1..a8
		if n == 0 {
			buf.WriteString("\ts.a1, s.a2, s.a3, s.a4, s.a5, s.a6, s.a7, s.a8 = 0, 0, 0, 0, 0, 0, 0, 0\n")
		} else if n <= 8 {
			// Set used args
			parts := make([]string, 8)
			for i := range 8 {
				if i < n {
					parts[i] = fmt.Sprintf("a%d", i+1)
				} else {
					parts[i] = "0"
				}
			}
			fmt.Fprintf(buf, "\ts.a1, s.a2, s.a3, s.a4, s.a5, s.a6, s.a7, s.a8 = %s\n", strings.Join(parts, ", "))
		} else {
			// All 8 used
			buf.WriteString("\ts.a1, s.a2, s.a3, s.a4, s.a5, s.a6, s.a7, s.a8 = a1, a2, a3, a4, a5, a6, a7, a8\n")
		}

		// Set a9..a15 overflow
		if n > 8 {
			overflow := make([]string, n-8)
			for i := 8; i < n; i++ {
				overflow[i-8] = fmt.Sprintf("a%d", i+1)
			}
			fields := []string{"s.a9", "s.a10", "s.a11", "s.a12", "s.a13", "s.a14", "s.a15"}
			// Set used overflow
			if len(overflow) > 0 {
				usedFields := fields[:len(overflow)]
				fmt.Fprintf(buf, "\t%s = %s\n", strings.Join(usedFields, ", "), strings.Join(overflow, ", "))
			}
			// Zero remaining
			remaining := fields[len(overflow):]
			if len(remaining) > 0 {
				zeros := make([]string, len(remaining))
				for i := range zeros {
					zeros[i] = "0"
				}
				fmt.Fprintf(buf, "\t%s = %s\n", strings.Join(remaining, ", "), strings.Join(zeros, ", "))
			}
		}

		buf.WriteString("\ts.f1, s.f2, s.f3, s.f4, s.f5, s.f6, s.f7, s.f8 = 0, 0, 0, 0, 0, 0, 0, 0\n")
		buf.WriteString("\ts.arm64_r8 = 0\n")
		buf.WriteString("\truntime_cgocall(syscall15XABI0, unsafe.Pointer(s))\n")
		buf.WriteString("\tr := s.a1\n")
		buf.WriteString("\tthePool.Put(s)\n")
		buf.WriteString("\treturn r\n")
		buf.WriteString("}\n\n")
	}
}

// writeFastCallIF emits the shared int+float backend.
func writeFastCallIF(buf *bytes.Buffer) {
	fmt.Fprintf(buf, `// fastCallIF calls cfn with numInts integer args (in a1..a15) and numFloats
// float args (pre-converted to bits in f1..f8). This is the shared backend
// for all fast-path float closures.
func fastCallIF(cfn uintptr, ints [%d]uintptr, numInts int, floats [8]uintptr, numFloats int) uintptr {
	s := thePool.Get().(*syscall15Args)
	s.fn = cfn
	// Set integer args
	switch {
	case numInts >= 8:
		s.a1, s.a2, s.a3, s.a4, s.a5, s.a6, s.a7, s.a8 = ints[0], ints[1], ints[2], ints[3], ints[4], ints[5], ints[6], ints[7]
		switch numInts {
		case 8:
			s.a9, s.a10, s.a11, s.a12, s.a13, s.a14, s.a15 = 0, 0, 0, 0, 0, 0, 0
		case 9:
			s.a9 = ints[8]
			s.a10, s.a11, s.a12, s.a13, s.a14, s.a15 = 0, 0, 0, 0, 0, 0
`, maxIntArgs)
	// Only need to handle up to maxIntArgs overflow slots now (was 14 before)
	for ni := 10; ni <= maxIntArgs; ni++ {
		fmt.Fprintf(buf, "\t\tcase %d:\n", ni)
		parts := make([]string, ni-8)
		for i := 8; i < ni; i++ {
			parts[i-8] = fmt.Sprintf("ints[%d]", i)
		}
		fields := []string{"s.a9", "s.a10", "s.a11", "s.a12", "s.a13", "s.a14", "s.a15"}
		usedFields := fields[:ni-8]
		fmt.Fprintf(buf, "\t\t\t%s = %s\n", strings.Join(usedFields, ", "), strings.Join(parts, ", "))
		remaining := fields[ni-8:]
		if len(remaining) > 0 {
			zeros := make([]string, len(remaining))
			for i := range zeros {
				zeros[i] = "0"
			}
			fmt.Fprintf(buf, "\t\t\t%s = %s\n", strings.Join(remaining, ", "), strings.Join(zeros, ", "))
		}
	}

	buf.WriteString(`		}
	default:
		s.a1 = ints[0]
		s.a2 = ints[1]
		s.a3 = ints[2]
		s.a4 = ints[3]
		s.a5 = ints[4]
		s.a6 = ints[5]
		s.a7 = ints[6]
		s.a8 = 0
		s.a9, s.a10, s.a11, s.a12, s.a13, s.a14, s.a15 = 0, 0, 0, 0, 0, 0, 0
	}
	// Set float args
	s.f1 = floats[0]
	s.f2 = floats[1]
	s.f3 = floats[2]
	s.f4 = floats[3]
	s.f5 = floats[4]
	s.f6 = floats[5]
	s.f7 = floats[6]
	s.f8 = floats[7]
	s.arm64_r8 = 0
	runtime_cgocall(syscall15XABI0, unsafe.Pointer(s))
	r := s.a1
	thePool.Put(s)
	return r
}

`)
}

// writeRegisterFastFuncFloat emits the trailing-float dispatcher.
func writeRegisterFastFuncFloat(buf *bytes.Buffer) {
	fmt.Fprintf(buf, `// registerFastFuncFloat sets fn to a zero-allocation closure for functions
// with numInts integer args followed by numFloats trailing float args.
func registerFastFuncFloat(fn reflect.Value, cfn uintptr, ty reflect.Type, numInts, numFloats int, hasReturn bool) {
	if numFloats == 1 {
		isFloat32 := ty.In(numInts).Kind() == reflect.Float32
		if isFloat32 {
			registerFastFuncFloat32x1(fn, cfn, numInts, hasReturn)
		} else {
			registerFastFuncFloat64x1(fn, cfn, numInts, hasReturn)
		}
		return
	}
	registerFastFuncFloatN(fn, cfn, ty, numInts, numFloats, hasReturn)
}

`)
}

// writeRegisterFastFuncFloat32x1 emits N ints + 1 trailing float32 closures.
func writeRegisterFastFuncFloat32x1(buf *bytes.Buffer) {
	maxTrailingInts := maxIntArgs - 1 // 9: at most 9 ints + 1 float = 10 total
	buf.WriteString("// registerFastFuncFloat32x1 handles N int args + 1 trailing float32.\n")
	buf.WriteString("func registerFastFuncFloat32x1(fn reflect.Value, cfn uintptr, numInts int, hasReturn bool) {\n")
	buf.WriteString("\tswitch numInts {\n")

	for n := 0; n <= maxTrailingInts; n++ {
		fmt.Fprintf(buf, "\tcase %d:\n", n)

		intParams := ""
		if n > 0 {
			intParams = argList(n) + " uintptr, "
		}

		var intsInit string
		if n == 0 {
			intsInit = fmt.Sprintf("var ints [%d]uintptr", maxIntArgs)
		} else {
			intsInit = fmt.Sprintf("ints := [%d]uintptr{%s}", maxIntArgs, argList(n))
		}

		// with return
		fmt.Fprintf(buf, "\t\tif hasReturn {\n")
		fmt.Fprintf(buf, "\t\t\timpl := func(%sf1 float32) uintptr {\n", intParams)
		fmt.Fprintf(buf, "\t\t\t\t%s\n", intsInit)
		buf.WriteString("\t\t\t\tvar floats [8]uintptr\n")
		buf.WriteString("\t\t\t\tfloats[0] = uintptr(math.Float32bits(f1))\n")
		fmt.Fprintf(buf, "\t\t\t\treturn fastCallIF(cfn, ints, %d, floats, 1)\n", n)
		buf.WriteString("\t\t\t}\n")
		buf.WriteString("\t\t\tforceFuncPtr(fn, &impl)\n")
		fmt.Fprintf(buf, "\t\t} else {\n")

		// without return
		fmt.Fprintf(buf, "\t\t\timpl := func(%sf1 float32) {\n", intParams)
		fmt.Fprintf(buf, "\t\t\t\t%s\n", intsInit)
		buf.WriteString("\t\t\t\tvar floats [8]uintptr\n")
		buf.WriteString("\t\t\t\tfloats[0] = uintptr(math.Float32bits(f1))\n")
		fmt.Fprintf(buf, "\t\t\t\tfastCallIF(cfn, ints, %d, floats, 1)\n", n)
		buf.WriteString("\t\t\t}\n")
		buf.WriteString("\t\t\tforceFuncPtr(fn, &impl)\n")
		buf.WriteString("\t\t}\n")
	}
	buf.WriteString("\t}\n}\n\n")
}

// writeRegisterFastFuncFloat64x1 emits N ints + 1 trailing float64 closures.
func writeRegisterFastFuncFloat64x1(buf *bytes.Buffer) {
	maxTrailingInts := maxIntArgs - 1
	buf.WriteString("// registerFastFuncFloat64x1 handles N int args + 1 trailing float64.\n")
	buf.WriteString("func registerFastFuncFloat64x1(fn reflect.Value, cfn uintptr, numInts int, hasReturn bool) {\n")
	buf.WriteString("\tswitch numInts {\n")

	for n := 0; n <= maxTrailingInts; n++ {
		fmt.Fprintf(buf, "\tcase %d:\n", n)

		intParams := ""
		if n > 0 {
			intParams = argList(n) + " uintptr, "
		}

		var intsInit string
		if n == 0 {
			intsInit = fmt.Sprintf("var ints [%d]uintptr", maxIntArgs)
		} else {
			intsInit = fmt.Sprintf("ints := [%d]uintptr{%s}", maxIntArgs, argList(n))
		}

		fmt.Fprintf(buf, "\t\tif hasReturn {\n")
		fmt.Fprintf(buf, "\t\t\timpl := func(%sf1 float64) uintptr {\n", intParams)
		fmt.Fprintf(buf, "\t\t\t\t%s\n", intsInit)
		buf.WriteString("\t\t\t\tvar floats [8]uintptr\n")
		buf.WriteString("\t\t\t\tfloats[0] = uintptr(math.Float64bits(f1))\n")
		fmt.Fprintf(buf, "\t\t\t\treturn fastCallIF(cfn, ints, %d, floats, 1)\n", n)
		buf.WriteString("\t\t\t}\n")
		buf.WriteString("\t\t\tforceFuncPtr(fn, &impl)\n")
		fmt.Fprintf(buf, "\t\t} else {\n")

		fmt.Fprintf(buf, "\t\t\timpl := func(%sf1 float64) {\n", intParams)
		fmt.Fprintf(buf, "\t\t\t\t%s\n", intsInit)
		buf.WriteString("\t\t\t\tvar floats [8]uintptr\n")
		buf.WriteString("\t\t\t\tfloats[0] = uintptr(math.Float64bits(f1))\n")
		fmt.Fprintf(buf, "\t\t\t\tfastCallIF(cfn, ints, %d, floats, 1)\n", n)
		buf.WriteString("\t\t\t}\n")
		buf.WriteString("\t\t\tforceFuncPtr(fn, &impl)\n")
		buf.WriteString("\t\t}\n")
	}
	buf.WriteString("\t}\n}\n\n")
}

// writeRegisterFastFuncInterleavedFloat32x1 emits closures for 1 float32 at any non-trailing position.
func writeRegisterFastFuncInterleavedFloat32x1(buf *bytes.Buffer) {
	buf.WriteString(`// registerFastFuncInterleavedFloat32x1 sets fn to a zero-allocation closure
// for functions with totalArgs parameters where exactly one is float32 at
// position floatPos (not the last position — trailing floats are handled by
// registerFastFuncFloat32x1).
func registerFastFuncInterleavedFloat32x1(fn reflect.Value, cfn uintptr, totalArgs, floatPos int, hasReturn bool) {
	switch totalArgs {
`)
	for totalArgs := 2; totalArgs <= maxIntArgs; totalArgs++ {
		fmt.Fprintf(buf, "\tcase %d:\n", totalArgs)
		fmt.Fprintf(buf, "\t\tswitch floatPos {\n")

		for floatPos := 0; floatPos <= totalArgs-2; floatPos++ {
			numInts := totalArgs - 1
			fmt.Fprintf(buf, "\t\tcase %d:\n", floatPos)

			fmt.Fprintf(buf, "\t\t\tif hasReturn {\n")
			fmt.Fprintf(buf, "\t\t\t\timpl := func(%s) uintptr {\n", interleavedParams(totalArgs, floatPos))
			fmt.Fprintf(buf, "\t\t\t\t\tints := [%d]uintptr{%s}\n", maxIntArgs, interleavedIntArgs(totalArgs))
			buf.WriteString("\t\t\t\t\tvar floats [8]uintptr\n")
			buf.WriteString("\t\t\t\t\tfloats[0] = uintptr(math.Float32bits(f1))\n")
			fmt.Fprintf(buf, "\t\t\t\t\treturn fastCallIF(cfn, ints, %d, floats, 1)\n", numInts)
			buf.WriteString("\t\t\t\t}\n")
			buf.WriteString("\t\t\t\tforceFuncPtr(fn, &impl)\n")
			buf.WriteString("\t\t\t} else {\n")

			fmt.Fprintf(buf, "\t\t\t\timpl := func(%s) {\n", interleavedParams(totalArgs, floatPos))
			fmt.Fprintf(buf, "\t\t\t\t\tints := [%d]uintptr{%s}\n", maxIntArgs, interleavedIntArgs(totalArgs))
			buf.WriteString("\t\t\t\t\tvar floats [8]uintptr\n")
			buf.WriteString("\t\t\t\t\tfloats[0] = uintptr(math.Float32bits(f1))\n")
			fmt.Fprintf(buf, "\t\t\t\t\tfastCallIF(cfn, ints, %d, floats, 1)\n", numInts)
			buf.WriteString("\t\t\t\t}\n")
			buf.WriteString("\t\t\t\tforceFuncPtr(fn, &impl)\n")
			buf.WriteString("\t\t\t}\n")
		}

		fmt.Fprintf(buf, "\t\t}\n")
	}
	buf.WriteString("\t}\n}\n\n")
}

// interleavedParams returns "a1 uintptr, f1 float32, a2, a3 uintptr" etc.
func interleavedParams(totalArgs, floatPos int) string {
	var parts []string
	intIdx := 1
	for i := range totalArgs {
		if i == floatPos {
			parts = append(parts, "f1 float32")
		} else {
			parts = append(parts, fmt.Sprintf("a%d uintptr", intIdx))
			intIdx++
		}
	}
	return strings.Join(parts, ", ")
}

// interleavedIntArgs returns "a1, a2, ..., a{numInts}" for the int args.
func interleavedIntArgs(totalArgs int) string {
	numInts := totalArgs - 1
	parts := make([]string, numInts)
	for i := range numInts {
		parts[i] = fmt.Sprintf("a%d", i+1)
	}
	return strings.Join(parts, ", ")
}

// writeRegisterFastFuncFloatN emits the MakeFunc fallback for multi/interleaved floats.
func writeRegisterFastFuncFloatN(buf *bytes.Buffer) {
	fmt.Fprintf(buf, `// registerFastFuncFloatN handles functions with interleaved or multiple float args.
// Falls back to reflect.MakeFunc since the combinatorial explosion of
// concrete closures is not worth the code size.
func registerFastFuncFloatN(fn reflect.Value, cfn uintptr, ty reflect.Type, numInts, numFloats int, hasReturn bool) {
	numIn := ty.NumIn()
	v := reflect.MakeFunc(ty, func(args []reflect.Value) []reflect.Value {
		var ints [%d]uintptr
		var floats [8]uintptr
		var ii, fi int
		for i := 0; i < numIn; i++ {
			switch ty.In(i).Kind() {
			case reflect.Float32:
				floats[fi] = uintptr(math.Float32bits(float32(args[i].Float())))
				fi++
			case reflect.Float64:
				floats[fi] = uintptr(math.Float64bits(args[i].Float()))
				fi++
			case reflect.Bool:
				if args[i].Bool() {
					ints[ii] = 1
				}
				ii++
			case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
				ints[ii] = uintptr(args[i].Int())
				ii++
			case reflect.Pointer, reflect.UnsafePointer:
				ints[ii] = args[i].Pointer()
				ii++
			default:
				ints[ii] = uintptr(args[i].Uint())
				ii++
			}
		}
		r := fastCallIF(cfn, ints, numInts, floats, numFloats)
		if !hasReturn {
			return nil
		}
		out := reflect.New(ty.Out(0)).Elem()
		switch ty.Out(0).Kind() {
		case reflect.Uintptr, reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
			out.SetUint(uint64(r))
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
			out.SetInt(int64(r))
		case reflect.Bool:
			out.SetBool(byte(r) != 0)
		case reflect.UnsafePointer:
			out.SetPointer(*(*unsafe.Pointer)(unsafe.Pointer(&r)))
		case reflect.Pointer:
			out = reflect.NewAt(ty.Out(0), unsafe.Pointer(&r)).Elem()
		}
		if len(args) > 0 {
			args[0] = out
			return args[:1]
		}
		return []reflect.Value{out}
	})
	fn.Set(v)
}

`, maxIntArgs)
}

// writeForceFuncPtr emits the unsafe func-ptr swap utility.
func writeForceFuncPtr(buf *bytes.Buffer) {
	buf.WriteString(`// forceFuncPtr assigns the function pointer in src to the reflect.Value dst,
// bypassing type checking. This is safe when the source and destination function
// types have identical ABI layouts (same number of pointer-sized args/returns).
func forceFuncPtr(dst reflect.Value, src any) {
	dstPtr := dst.Addr().UnsafePointer() // *func(...)
	srcPtr := (*unsafe.Pointer)(reflect.ValueOf(src).UnsafePointer())
	*(*unsafe.Pointer)(dstPtr) = *srcPtr
}
`)
}
