//go:build ignore

// gen_float.go generates the trailing-float fixed-arity syscall variants.
//
// It emits two files:
//
//	syscall_float.go    — Syscall0Float64x1 .. Syscall15Float64x1 (C double)
//	syscall_float32.go  — Syscall0Float32x1 .. Syscall15Float32x1 (C float)
//
// Each family calls a C function that takes N integer (or pointer) arguments
// and exactly one trailing floating-point argument. Run with:
//
//	go run gen_float.go
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"
)

const maxArity = 15

type variant struct {
	width  int    // 32 or 64
	file   string // output file
	goType string // float32 or float64
	bitsFn string // math.Float32bits or math.Float64bits
	cType  string // "float" or "double" (for docs)
	famDoc string // package-level family doc
}

func main() {
	variants := []variant{
		{
			width:  64,
			file:   "syscall_float.go",
			goType: "float64",
			bitsFn: "math.Float64bits",
			cType:  "double",
			famDoc: float64FamilyDoc,
		},
		{
			width:  32,
			file:   "syscall_float32.go",
			goType: "float32",
			bitsFn: "math.Float32bits",
			cType:  "float",
			famDoc: float32FamilyDoc,
		},
	}

	for _, v := range variants {
		src := generate(v)
		formatted, err := format.Source(src)
		if err != nil {
			fmt.Fprintf(os.Stderr, "format %s: %v\n%s", v.file, err, src)
			os.Exit(1)
		}
		if err := os.WriteFile(v.file, formatted, 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "write %s: %v\n", v.file, err)
			os.Exit(1)
		}
		fmt.Printf("wrote %s (%d funcs)\n", v.file, maxArity+1)
	}
}

func generate(v variant) []byte {
	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString(v.famDoc)
	for n := 0; n <= maxArity; n++ {
		writeFunc(&b, v, n)
	}
	return b.Bytes()
}

// writeFunc emits one Syscall<n>Float<width>x1 function.
func writeFunc(b *bytes.Buffer, v variant, n int) {
	name := fmt.Sprintf("Syscall%dFloat%dx1", n, v.width)

	// integer parameter list: a1, a2, ... aN
	ints := make([]string, n)
	for i := range ints {
		ints[i] = fmt.Sprintf("a%d", i+1)
	}

	// function signature
	var sig strings.Builder
	sig.WriteString("fn")
	for _, a := range ints {
		sig.WriteString(", " + a)
	}
	sig.WriteString(" uintptr, f1 " + v.goType)

	// Windows fallback argument list
	var winArgs strings.Builder
	winArgs.WriteString("fn")
	for _, a := range ints {
		winArgs.WriteString(", " + a)
	}
	winArgs.WriteString(", uintptr(" + v.bitsFn + "(f1))")

	// integer-slice assignment
	var assign string
	if n > 0 {
		lhs := make([]string, n)
		for i := range lhs {
			lhs[i] = fmt.Sprintf("tmp[%d]", i)
		}
		assign = strings.Join(lhs, ", ") + " = " + strings.Join(ints, ", ")
	}

	// doc comment
	intDesc := pluralizeInts(n)
	fmt.Fprintf(b, "\n// %s calls fn with %s and one trailing %s.\n", name, intDesc, v.cType)
	fmt.Fprintf(b, "// See the Syscall<N>Float%dx1 family documentation for details and caveats.\n", v.width)
	b.WriteString("//\n//go:uintptrescapes\n")
	fmt.Fprintf(b, "func %s(%s) (r1, r2, err uintptr) {\n", name, sig.String())
	b.WriteString("\tif fn == 0 {\n\t\tpanic(\"purego: fn is nil\")\n\t}\n")
	fmt.Fprintf(b, "\tif runtime.GOOS == \"windows\" {\n\t\treturn syscall_syscallN(%s)\n\t}\n", winArgs.String())
	b.WriteString("\tvar tmp [maxArgs]uintptr\n")
	if assign != "" {
		b.WriteString("\t" + assign + "\n")
	}
	b.WriteString("\tvar floats [maxArgs]uintptr\n")
	fmt.Fprintf(b, "\tfloats[0] = uintptr(%s(f1))\n", v.bitsFn)
	b.WriteString("\ts := syscall_SyscallN(fn, tmp[:], floats[:], 0)\n")
	b.WriteString("\tdefer thePool.Put(s)\n")
	b.WriteString("\treturn s.a1, s.a2, s.a3\n}\n")
}

func pluralizeInts(n int) string {
	switch n {
	case 0:
		return "no integer arguments"
	case 1:
		return "one integer argument"
	default:
		return fmt.Sprintf("%s integer arguments", numberWord(n))
	}
}

func numberWord(n int) string {
	words := []string{"zero", "one", "two", "three", "four", "five", "six", "seven",
		"eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen"}
	if n < len(words) {
		return words[n]
	}
	return fmt.Sprintf("%d", n)
}

const header = `// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The Ebitengine Authors

// Code generated by gen_float.go; DO NOT EDIT.

//go:build !386 && !arm && !ppc64le && (darwin || freebsd || linux || netbsd || windows)

package purego

import (
	"math"
	"runtime"
)
`

const float64FamilyDoc = `
// The Syscall<N>Float64x1 family is a set of fixed-arity variants of [SyscallN]
// for calling C functions that take N integer (or pointer) arguments and
// exactly one trailing double argument. Unlike [SyscallN], which cannot
// correctly call functions that mix integer and floating-point parameters,
// these variants place the integer arguments and the float argument in their
// respective register classes, matching the platform C ABI.
//
// The integer arguments a1..aN are passed in the integer argument registers in
// order; f1 is passed as a double in the first floating-point argument
// register. This is correct on platforms whose C ABI assigns integer and
// floating-point arguments to independent register files (such as the
// AArch64 AAPCS and the AMD64 System V ABI), regardless of where the float
// appears in the C declaration relative to the integer arguments. For
// example, a C function declared as
//
//	long f(long a, long b, double x, long c)
//
// is called as Syscall3Float64x1(fn, a, b, c, x): the three integer arguments
// are passed positionally and x is passed as the trailing double.
//
// The x1 suffix denotes a single trailing floating-point argument. Only this
// shape — N integers and exactly one trailing double — is provided. Multiple
// floating-point arguments, or more than eight floating-point arguments that
// would spill onto the stack, are not expressible through this family and are
// intentionally omitted; use [RegisterFunc] for those.
//
// On Windows the underlying helper cannot place a value in a floating-point
// register, so these variants fall back to passing the raw bits of f1 as an
// additional integer argument; they are correct only on platforms that use the
// purego funnel (see [SyscallN]).
`

const float32FamilyDoc = `
// The Syscall<N>Float32x1 family is the single-precision counterpart of the
// [Syscall0Float64x1] family. Each variant calls a C function that takes N
// integer (or pointer) arguments and exactly one trailing float (float32)
// argument.
//
// The integer arguments a1..aN are passed in the integer argument registers in
// order; f1 is passed as a single-precision float in the first floating-point
// argument register. On platforms whose C ABI assigns integer and
// floating-point arguments to independent register files (the AArch64 AAPCS and
// the AMD64 System V ABI), a float argument occupies the low 32 bits of the
// first floating-point register, so the float bits are written there directly;
// this is correct regardless of where the float appears in the C declaration
// relative to the integer arguments.
//
// The Syscall<N>Float32x1 and [Syscall0Float64x1] families are not
// interchangeable: a float bit pattern read by a double parameter (or the
// reverse) yields a different value. Match the family to whether the C function
// declares its scalar parameter as float or double.
//
// The x1 suffix denotes a single trailing floating-point argument. The same
// restrictions as the double family apply: only the shape of N integers and
// exactly one trailing float is provided; multiple floating-point arguments, or
// arguments that spill onto the stack, are not expressible and are intentionally
// omitted; use [RegisterFunc] for those.
//
// On Windows the underlying helper cannot place a value in a floating-point
// register, so these variants fall back to passing the raw bits of f1 as an
// additional integer argument; they are correct only on platforms that use the
// purego funnel (see [SyscallN]).
`
