// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The Ebitengine Authors

// Code generated by gen_float.go; DO NOT EDIT.

//go:build !386 && !arm && !ppc64le && (darwin || freebsd || linux || netbsd || windows)

package purego

import (
	"math"
	"runtime"
)

// The Syscall<N>Float32x1 family is the single-precision counterpart of the
// [Syscall0Float64x1] family. Each variant calls a C function that takes N
// integer (or pointer) arguments and exactly one trailing float (float32)
// argument.
//
// The integer arguments a1..aN are passed in the integer argument registers in
// order; f1 is passed as a single-precision float in the first floating-point
// argument register. On platforms whose C ABI assigns integer and
// floating-point arguments to independent register files (the AArch64 AAPCS and
// the AMD64 System V ABI), a float argument occupies the low 32 bits of the
// first floating-point register, so the float bits are written there directly;
// this is correct regardless of where the float appears in the C declaration
// relative to the integer arguments.
//
// The Syscall<N>Float32x1 and [Syscall0Float64x1] families are not
// interchangeable: a float bit pattern read by a double parameter (or the
// reverse) yields a different value. Match the family to whether the C function
// declares its scalar parameter as float or double.
//
// The x1 suffix denotes a single trailing floating-point argument. The same
// restrictions as the double family apply: only the shape of N integers and
// exactly one trailing float is provided; multiple floating-point arguments, or
// arguments that spill onto the stack, are not expressible and are intentionally
// omitted; use [RegisterFunc] for those.
//
// On Windows the underlying helper cannot place a value in a floating-point
// register, so these variants fall back to passing the raw bits of f1 as an
// additional integer argument; they are correct only on platforms that use the
// purego funnel (see [SyscallN]).

// Syscall0Float32x1 calls fn with no integer arguments and one trailing float.
// See the Syscall<N>Float32x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall0Float32x1(fn uintptr, f1 float32) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, uintptr(math.Float32bits(f1)))
	}
	var tmp [maxArgs]uintptr
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float32bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall1Float32x1 calls fn with one integer argument and one trailing float.
// See the Syscall<N>Float32x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall1Float32x1(fn, a1 uintptr, f1 float32) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, uintptr(math.Float32bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0] = a1
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float32bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall2Float32x1 calls fn with two integer arguments and one trailing float.
// See the Syscall<N>Float32x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall2Float32x1(fn, a1, a2 uintptr, f1 float32) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, uintptr(math.Float32bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1] = a1, a2
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float32bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall3Float32x1 calls fn with three integer arguments and one trailing float.
// See the Syscall<N>Float32x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall3Float32x1(fn, a1, a2, a3 uintptr, f1 float32) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, uintptr(math.Float32bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2] = a1, a2, a3
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float32bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall4Float32x1 calls fn with four integer arguments and one trailing float.
// See the Syscall<N>Float32x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall4Float32x1(fn, a1, a2, a3, a4 uintptr, f1 float32) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, uintptr(math.Float32bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3] = a1, a2, a3, a4
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float32bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall5Float32x1 calls fn with five integer arguments and one trailing float.
// See the Syscall<N>Float32x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall5Float32x1(fn, a1, a2, a3, a4, a5 uintptr, f1 float32) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, uintptr(math.Float32bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4] = a1, a2, a3, a4, a5
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float32bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall6Float32x1 calls fn with six integer arguments and one trailing float.
// See the Syscall<N>Float32x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall6Float32x1(fn, a1, a2, a3, a4, a5, a6 uintptr, f1 float32) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, uintptr(math.Float32bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5] = a1, a2, a3, a4, a5, a6
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float32bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall7Float32x1 calls fn with seven integer arguments and one trailing float.
// See the Syscall<N>Float32x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall7Float32x1(fn, a1, a2, a3, a4, a5, a6, a7 uintptr, f1 float32) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, a7, uintptr(math.Float32bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5], tmp[6] = a1, a2, a3, a4, a5, a6, a7
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float32bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall8Float32x1 calls fn with eight integer arguments and one trailing float.
// See the Syscall<N>Float32x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall8Float32x1(fn, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f1 float32) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, a7, a8, uintptr(math.Float32bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5], tmp[6], tmp[7] = a1, a2, a3, a4, a5, a6, a7, a8
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float32bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall9Float32x1 calls fn with nine integer arguments and one trailing float.
// See the Syscall<N>Float32x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall9Float32x1(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9 uintptr, f1 float32) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, uintptr(math.Float32bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5], tmp[6], tmp[7], tmp[8] = a1, a2, a3, a4, a5, a6, a7, a8, a9
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float32bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall10Float32x1 calls fn with ten integer arguments and one trailing float.
// See the Syscall<N>Float32x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall10Float32x1(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10 uintptr, f1 float32) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, uintptr(math.Float32bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5], tmp[6], tmp[7], tmp[8], tmp[9] = a1, a2, a3, a4, a5, a6, a7, a8, a9, a10
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float32bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall11Float32x1 calls fn with eleven integer arguments and one trailing float.
// See the Syscall<N>Float32x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall11Float32x1(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11 uintptr, f1 float32) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, uintptr(math.Float32bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5], tmp[6], tmp[7], tmp[8], tmp[9], tmp[10] = a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float32bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall12Float32x1 calls fn with twelve integer arguments and one trailing float.
// See the Syscall<N>Float32x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall12Float32x1(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12 uintptr, f1 float32) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, uintptr(math.Float32bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5], tmp[6], tmp[7], tmp[8], tmp[9], tmp[10], tmp[11] = a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float32bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall13Float32x1 calls fn with thirteen integer arguments and one trailing float.
// See the Syscall<N>Float32x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall13Float32x1(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13 uintptr, f1 float32) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, uintptr(math.Float32bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5], tmp[6], tmp[7], tmp[8], tmp[9], tmp[10], tmp[11], tmp[12] = a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float32bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall14Float32x1 calls fn with fourteen integer arguments and one trailing float.
// See the Syscall<N>Float32x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall14Float32x1(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14 uintptr, f1 float32) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, uintptr(math.Float32bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5], tmp[6], tmp[7], tmp[8], tmp[9], tmp[10], tmp[11], tmp[12], tmp[13] = a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float32bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall15Float32x1 calls fn with fifteen integer arguments and one trailing float.
// See the Syscall<N>Float32x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall15Float32x1(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15 uintptr, f1 float32) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, uintptr(math.Float32bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5], tmp[6], tmp[7], tmp[8], tmp[9], tmp[10], tmp[11], tmp[12], tmp[13], tmp[14] = a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float32bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}
