// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The Ebitengine Authors

// Code generated by gen_float.go; DO NOT EDIT.

//go:build !386 && !arm && !ppc64le && (darwin || freebsd || linux || netbsd || windows)

package purego

import (
	"math"
	"runtime"
)

// The Syscall<N>Float64x1 family is a set of fixed-arity variants of [SyscallN]
// for calling C functions that take N integer (or pointer) arguments and
// exactly one trailing double argument. Unlike [SyscallN], which cannot
// correctly call functions that mix integer and floating-point parameters,
// these variants place the integer arguments and the float argument in their
// respective register classes, matching the platform C ABI.
//
// The integer arguments a1..aN are passed in the integer argument registers in
// order; f1 is passed as a double in the first floating-point argument
// register. This is correct on platforms whose C ABI assigns integer and
// floating-point arguments to independent register files (such as the
// AArch64 AAPCS and the AMD64 System V ABI), regardless of where the float
// appears in the C declaration relative to the integer arguments. For
// example, a C function declared as
//
//	long f(long a, long b, double x, long c)
//
// is called as Syscall3Float64x1(fn, a, b, c, x): the three integer arguments
// are passed positionally and x is passed as the trailing double.
//
// The x1 suffix denotes a single trailing floating-point argument. Only this
// shape — N integers and exactly one trailing double — is provided. Multiple
// floating-point arguments, or more than eight floating-point arguments that
// would spill onto the stack, are not expressible through this family and are
// intentionally omitted; use [RegisterFunc] for those.
//
// On Windows the underlying helper cannot place a value in a floating-point
// register, so these variants fall back to passing the raw bits of f1 as an
// additional integer argument; they are correct only on platforms that use the
// purego funnel (see [SyscallN]).

// Syscall0Float64x1 calls fn with no integer arguments and one trailing double.
// See the Syscall<N>Float64x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall0Float64x1(fn uintptr, f1 float64) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, uintptr(math.Float64bits(f1)))
	}
	var tmp [maxArgs]uintptr
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float64bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall1Float64x1 calls fn with one integer argument and one trailing double.
// See the Syscall<N>Float64x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall1Float64x1(fn, a1 uintptr, f1 float64) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, uintptr(math.Float64bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0] = a1
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float64bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall2Float64x1 calls fn with two integer arguments and one trailing double.
// See the Syscall<N>Float64x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall2Float64x1(fn, a1, a2 uintptr, f1 float64) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, uintptr(math.Float64bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1] = a1, a2
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float64bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall3Float64x1 calls fn with three integer arguments and one trailing double.
// See the Syscall<N>Float64x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall3Float64x1(fn, a1, a2, a3 uintptr, f1 float64) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, uintptr(math.Float64bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2] = a1, a2, a3
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float64bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall4Float64x1 calls fn with four integer arguments and one trailing double.
// See the Syscall<N>Float64x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall4Float64x1(fn, a1, a2, a3, a4 uintptr, f1 float64) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, uintptr(math.Float64bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3] = a1, a2, a3, a4
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float64bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall5Float64x1 calls fn with five integer arguments and one trailing double.
// See the Syscall<N>Float64x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall5Float64x1(fn, a1, a2, a3, a4, a5 uintptr, f1 float64) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, uintptr(math.Float64bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4] = a1, a2, a3, a4, a5
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float64bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall6Float64x1 calls fn with six integer arguments and one trailing double.
// See the Syscall<N>Float64x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall6Float64x1(fn, a1, a2, a3, a4, a5, a6 uintptr, f1 float64) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, uintptr(math.Float64bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5] = a1, a2, a3, a4, a5, a6
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float64bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall7Float64x1 calls fn with seven integer arguments and one trailing double.
// See the Syscall<N>Float64x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall7Float64x1(fn, a1, a2, a3, a4, a5, a6, a7 uintptr, f1 float64) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, a7, uintptr(math.Float64bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5], tmp[6] = a1, a2, a3, a4, a5, a6, a7
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float64bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall8Float64x1 calls fn with eight integer arguments and one trailing double.
// See the Syscall<N>Float64x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall8Float64x1(fn, a1, a2, a3, a4, a5, a6, a7, a8 uintptr, f1 float64) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, a7, a8, uintptr(math.Float64bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5], tmp[6], tmp[7] = a1, a2, a3, a4, a5, a6, a7, a8
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float64bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall9Float64x1 calls fn with nine integer arguments and one trailing double.
// See the Syscall<N>Float64x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall9Float64x1(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9 uintptr, f1 float64) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, uintptr(math.Float64bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5], tmp[6], tmp[7], tmp[8] = a1, a2, a3, a4, a5, a6, a7, a8, a9
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float64bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall10Float64x1 calls fn with ten integer arguments and one trailing double.
// See the Syscall<N>Float64x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall10Float64x1(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10 uintptr, f1 float64) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, uintptr(math.Float64bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5], tmp[6], tmp[7], tmp[8], tmp[9] = a1, a2, a3, a4, a5, a6, a7, a8, a9, a10
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float64bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall11Float64x1 calls fn with eleven integer arguments and one trailing double.
// See the Syscall<N>Float64x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall11Float64x1(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11 uintptr, f1 float64) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, uintptr(math.Float64bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5], tmp[6], tmp[7], tmp[8], tmp[9], tmp[10] = a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float64bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall12Float64x1 calls fn with twelve integer arguments and one trailing double.
// See the Syscall<N>Float64x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall12Float64x1(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12 uintptr, f1 float64) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, uintptr(math.Float64bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5], tmp[6], tmp[7], tmp[8], tmp[9], tmp[10], tmp[11] = a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float64bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall13Float64x1 calls fn with thirteen integer arguments and one trailing double.
// See the Syscall<N>Float64x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall13Float64x1(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13 uintptr, f1 float64) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, uintptr(math.Float64bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5], tmp[6], tmp[7], tmp[8], tmp[9], tmp[10], tmp[11], tmp[12] = a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float64bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall14Float64x1 calls fn with fourteen integer arguments and one trailing double.
// See the Syscall<N>Float64x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall14Float64x1(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14 uintptr, f1 float64) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, uintptr(math.Float64bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5], tmp[6], tmp[7], tmp[8], tmp[9], tmp[10], tmp[11], tmp[12], tmp[13] = a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float64bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}

// Syscall15Float64x1 calls fn with fifteen integer arguments and one trailing double.
// See the Syscall<N>Float64x1 family documentation for details and caveats.
//
//go:uintptrescapes
func Syscall15Float64x1(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15 uintptr, f1 float64) (r1, r2, err uintptr) {
	if fn == 0 {
		panic("purego: fn is nil")
	}
	if runtime.GOOS == "windows" {
		return syscall_syscallN(fn, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, uintptr(math.Float64bits(f1)))
	}
	var tmp [maxArgs]uintptr
	tmp[0], tmp[1], tmp[2], tmp[3], tmp[4], tmp[5], tmp[6], tmp[7], tmp[8], tmp[9], tmp[10], tmp[11], tmp[12], tmp[13], tmp[14] = a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15
	var floats [maxArgs]uintptr
	floats[0] = uintptr(math.Float64bits(f1))
	s := syscall_SyscallN(fn, tmp[:], floats[:], 0)
	defer thePool.Put(s)
	return s.a1, s.a2, s.a3
}
