// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2025 The Ebitengine Authors
// Code generated by internal/genpuregotests; DO NOT EDIT.
//
// ABI Test C Functions
// These functions return string representations of their arguments to verify
// correct ABI implementation across different platforms.

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>


char* test_11_int32(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11) {
    char* result = malloc(1024);
    snprintf(result, 1024, "%d:%d:%d:%d:%d:%d:%d:%d:%d:%d:%d", (int)a1, (int)a2, (int)a3, (int)a4, (int)a5, (int)a6, (int)a7, (int)a8, (int)a9, (int)a10, (int)a11);
    return result;
}


char* test_12_int32(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12) {
    char* result = malloc(1024);
    snprintf(result, 1024, "%d:%d:%d:%d:%d:%d:%d:%d:%d:%d:%d:%d", (int)a1, (int)a2, (int)a3, (int)a4, (int)a5, (int)a6, (int)a7, (int)a8, (int)a9, (int)a10, (int)a11, (int)a12);
    return result;
}


char* test_mixed_8i32_1f32_1i32(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, float f9, int32_t a10) {
    char* result = malloc(1024);
    snprintf(result, 1024, "%d:%d:%d:%d:%d:%d:%d:%d:%f:%d", (int)a1, (int)a2, (int)a3, (int)a4, (int)a5, (int)a6, (int)a7, (int)a8, (double)f9, (int)a10);
    return result;
}


char* test_8i32_3strings(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, const char* s9, const char* s10, const char* s11) {
    char* result = malloc(1024);
    snprintf(result, 1024, "%d:%d:%d:%d:%d:%d:%d:%d:%s:%s:%s", (int)a1, (int)a2, (int)a3, (int)a4, (int)a5, (int)a6, (int)a7, (int)a8, (const char*)s9, (const char*)s10, (const char*)s11);
    return result;
}


char* test_mixed_stack_strings(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, const char* s9, int32_t a10, const char* s11) {
    char* result = malloc(1024);
    snprintf(result, 1024, "%d:%d:%d:%d:%d:%d:%d:%d:%s:%d:%s", (int)a1, (int)a2, (int)a3, (int)a4, (int)a5, (int)a6, (int)a7, (int)a8, (const char*)s9, (int)a10, (const char*)s11);
    return result;
}


char* test_string_only_10(const char* s1, const char* s2, const char* s3, const char* s4, const char* s5, const char* s6, const char* s7, const char* s8, const char* s9, const char* s10) {
    char* result = malloc(1024);
    snprintf(result, 1024, "%s:%s:%s:%s:%s:%s:%s:%s:%s:%s", (const char*)s1, (const char*)s2, (const char*)s3, (const char*)s4, (const char*)s5, (const char*)s6, (const char*)s7, (const char*)s8, (const char*)s9, (const char*)s10);
    return result;
}


char* test_1i32_10strings(int32_t a1, const char* s2, const char* s3, const char* s4, const char* s5, const char* s6, const char* s7, const char* s8, const char* s9, const char* s10, const char* s11) {
    char* result = malloc(1024);
    snprintf(result, 1024, "%d:%s:%s:%s:%s:%s:%s:%s:%s:%s:%s", (int)a1, (const char*)s2, (const char*)s3, (const char*)s4, (const char*)s5, (const char*)s6, (const char*)s7, (const char*)s8, (const char*)s9, (const char*)s10, (const char*)s11);
    return result;
}


char* test_mixed_bool_string(bool b1, bool b2, bool b3, bool b4, bool b5, bool b6, bool b7, bool b8, const char* s9, const char* s10, const char* s11) {
    char* result = malloc(1024);
    snprintf(result, 1024, "%d:%d:%d:%d:%d:%d:%d:%d:%s:%s:%s", (int)b1, (int)b2, (int)b3, (int)b4, (int)b5, (int)b6, (int)b7, (int)b8, (const char*)s9, (const char*)s10, (const char*)s11);
    return result;
}


char* test_float_then_int(float f1, float f2, float f3, float f4, float f5, float f6, float f7, float f8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16) {
    char* result = malloc(1024);
    snprintf(result, 1024, "%f:%f:%f:%f:%f:%f:%f:%f:%d:%d:%d:%d:%d:%d:%d:%d", (double)f1, (double)f2, (double)f3, (double)f4, (double)f5, (double)f6, (double)f7, (double)f8, (int)a9, (int)a10, (int)a11, (int)a12, (int)a13, (int)a14, (int)a15, (int)a16);
    return result;
}


char* test_mixed_f32_f64_mix(float f1, float f2, float f3, float f4, double f5, double f6, double f7, double f8, float f9, float f10) {
    char* result = malloc(1024);
    snprintf(result, 1024, "%f:%f:%f:%f:%lf:%lf:%lf:%lf:%f:%f", (double)f1, (double)f2, (double)f3, (double)f4, (double)f5, (double)f6, (double)f7, (double)f8, (double)f9, (double)f10);
    return result;
}



